export const MenuLevelOne = {
    ADMIN: 'ADMIN',
    QUIZ: 'QUIZ',
    EXAM: 'EXAM',
    CONTENT: 'CONTENT',
    SECTION: 'SECTION',
    ROUTE: 'ROUTE',
    ADMINISTRATION: 'ADMINISTRATION',
    CENSOR: 'CENSOR'
}
export const MenuLevelTwo = {
    VOCABULARY: 'VOCABULARY',
    CATEGORY: 'CATEGORY',
    TAG: 'TAG',
    POST: 'POST',
    QUESTIONBANK: 'QUESTIONBANK',
    CERTIFICATE: 'CERTIFICATe'
}